import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es" | "pt" | "de" | "fr" | "th";

interface LanguageInfo {
  code: Language;
  name: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "pt", name: "Português", flag: "🇧🇷" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.about": "About",
    "nav.shop": "Shop",
    "nav.videos": "Videos",
    "nav.destinations": "Destinations",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Experience",
    "nav.bar": "The Bar",
    "nav.subscribe": "Subscribe",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Travel. Culture. Wolfgang.",
    "hero.shop": "Shop Perfumes",
    "hero.youtube": "Watch on YouTube",
    "hero.experience": "Experience Brazil",
    "about.pre": "Who is Roberto?",
    "about.title1": "The Man Behind",
    "about.title2": "The Missions",
    "about.quote": "I am not trying to be a clean influencer. I am just a guy who refused to stay where he was placed and decided to turn his crazy life into a living, breathing story.",
    "about.bio1": "I grew up in Sweden, but I never really felt like I belonged anywhere. My roots are Macedonian and Roma, my reality was Swedish suburbs, and my head was always somewhere else in the world. I did the normal life thing for a while, even worked at Volvo, but deep down I knew I was not built for clocking in and out.",
    "about.bio2": "Brazil changed everything for me. The first time I came, I felt more at home on the streets of Rio than I ever did in Sweden. The favelas, the beaches, the music, the way people look you in the eyes and speak from the heart. Thailand became the other side of my story — the nightlife, the madness of Pattaya and Bangkok, the characters you meet at four in the morning.",
    "about.bio3": "My channel is basically my life turned up to 100. I speak a lot of languages, I connect with people fast, and I do not script anything. When you watch Roberto Vs The World, I want you to feel like you are right next to me — in the taxi, in the club, on the beach, in the middle of the chaos.",
    "about.subs": "YouTube Subscribers",
    "videos.pre": "Latest Adventures",
    "videos.title": "Featured Videos",
    "videos.shorts": "Latest Shorts",
    "videos.all": "See All Videos",
    "videos.allShorts": "See All Shorts",
    "dest.pre": "Where Roberto Goes",
    "dest.title": "Destinations",
    "shop.pre": "Exclusive Collection",
    "shop.title": "Fruten Fraten® Perfumes",
    "shop.subtitle": "Carry the spirit of adventure with you. Each fragrance tells a chapter of the journey.",
    "shop.now": "Shop Now",
    "shop.notify": "Notify Me",
    "shop.visit": "Visit Full Store",
    "ff.origin": "Born in a coffee shop in Barcelona — became a worldwide movement",
    "ff.story1": "Fruten Fraten is not from a dictionary. It is not Swedish, not Portuguese, not Thai — it is something I invented with a friend in a coffee shop in Barcelona when we were young, high, and dreaming about a bigger life.",
    "ff.story2": "At first it was just an inside joke between friends. Then I started saying it online, screaming it into the camera, and suddenly people all over Brazil, Thailand, Europe and the rest of the world were shouting it back at me. It became a code, a feeling, a way of living — it means live full, do not overthink, create your own rules, enjoy the madness but keep your heart.",
    "ff.story3": "People ask me all the time what Fruten Fraten really means. The truth is, if you have to overanalyze it, you do not get it yet. It is that feeling when you are on a rooftop in Rio at sunset with music playing and you know you are exactly where you need to be.",
    "ff.bold": "Live Bold",
    "ff.bold.sub": "No comfort zones allowed",
    "ff.real": "Stay Real",
    "ff.real.sub": "Authentic connections only",
    "ff.party": "Party Hard",
    "ff.party.sub": "Life is a celebration",
    "wolf.pre": "The Pack",
    "wolf.title": "Wolfgang",
    "wolf.desc": "The Wolfgang isn't just a fanbase — it's a global tribe of adventurers, dreamers, and real ones who ride with Roberto through every mission.",
    "wolf.yt.desc": "Watch the latest travel vlogs, missions, and behind-the-scenes content.",
    "wolf.ig.desc": "Follow for daily stories, travel photos, and Wolfgang updates.",
    "wolf.tt.desc": "Quick clips, viral moments, and chaotic energy from around the world.",
    "wolf.tw.desc": "Live streams, real-time adventures, and hanging with the Wolfgang.",
    "wolf.join": "Join the Pack",
    "wolf.join.desc": "Become a true Wolfgang member. Subscribe, follow, and be part of the global adventure.",
    "bar.pre": "The Spot",
    "bar.intro": "Where the Fruten Fraten lifestyle comes to life. Roberto's own bar in the heart of Koh Samui, Thailand.",
    "bar.desc": "What started as a dream became reality on the island of Koh Samui. The Fruten Fraten Bar is where Roberto's videos play on the screens, signature cocktails flow, and people from all over the world pull up because they saw him online. It's not just a bar — it's a headquarters for the Wolfgang in Southeast Asia.",
    "bar.vibe": "Neon lights, graffiti walls, a DJ booth, and that unmistakable energy you know from the videos. If you're on the island, this is where you need to be.",
    "bar.location": "Location",
    "bar.hours": "Opening Hours",
    "bar.music": "Music",
    "bar.feature": "The Experience",
    "bar.cta": "Pull up to the bar 🔥",
    "bar.directions": "Get Directions",
    "exp.hero": "Experience Brazil",
    "exp.title": "A Day in Brazil",
    "exp.style": "Roberto Style",
    "exp.subtitle": "Not a tour. A real experience.",
    "exp.hook": "Ever wondered what a real day in Brazil feels like?",
    "exp.desc": "Join Roberto for a half-day or full-day experience through beaches, local food spots, hidden gems, and authentic nightlife. This isn't a tour guide holding a flag. This is Brazil through real connections.",
    "exp.day": "Day Experience",
    "exp.night": "Night Experience",
    "exp.full": "Full Roberto Mode",
    "exp.apply": "Apply for the Experience",
    "exp.form.name": "Your Name",
    "exp.form.dates": "Travel Dates",
    "exp.form.group": "Group Size",
    "exp.form.vibe": "What vibe are you looking for?",
    "exp.form.submit": "Request Your Date",
    "footer.rights": "All rights reserved.",
  },
  es: {
    "nav.about": "Acerca de",
    "nav.shop": "Tienda",
    "nav.videos": "Videos",
    "nav.destinations": "Destinos",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Experiencia",
    "nav.bar": "El Bar",
    "nav.subscribe": "Suscríbete",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Viaje. Cultura. Wolfgang.",
    "hero.shop": "Comprar Perfumes",
    "hero.youtube": "Ver en YouTube",
    "hero.experience": "Experiencia Brasil",
    "about.pre": "¿Quién es Roberto?",
    "about.title1": "El Hombre Detrás",
    "about.title2": "De Las Misiones",
    "about.quote": "No intento ser un influencer limpio. Solo soy un tipo que se negó a quedarse donde lo pusieron y decidió convertir su vida loca en una historia viva.",
    "about.bio1": "Crecí en Suecia, pero nunca sentí que perteneciera a ningún lugar. Mis raíces son macedonias y romaníes, mi realidad eran los suburbios suecos, y mi cabeza siempre estaba en otro lugar del mundo.",
    "about.bio2": "Brasil lo cambió todo para mí. La primera vez que vine, me sentí más en casa en las calles de Río que nunca en Suecia. Tailandia se convirtió en el otro lado de mi historia — la vida nocturna, la locura de Pattaya y Bangkok.",
    "about.bio3": "Mi canal es básicamente mi vida al 100. Hablo muchos idiomas, conecto con la gente rápido, y no escribo guión. Cuando ves Roberto Vs The World, quiero que sientas que estás justo a mi lado.",
    "about.subs": "Suscriptores de YouTube",
    "videos.pre": "Últimas Aventuras",
    "videos.title": "Videos Destacados",
    "videos.shorts": "Últimos Shorts",
    "videos.all": "Ver Todos los Videos",
    "videos.allShorts": "Ver Todos los Shorts",
    "shop.pre": "Colección Exclusiva",
    "shop.title": "Perfumes Fruten Fraten®",
    "shop.subtitle": "Lleva el espíritu de la aventura contigo.",
    "shop.now": "Comprar",
    "shop.notify": "Notificarme",
    "shop.visit": "Visitar Tienda Completa",
    "ff.origin": "Nacido en una cafetería en Barcelona — se convirtió en un movimiento mundial",
    "ff.story1": "Fruten Fraten no viene de un diccionario. Lo inventé con un amigo en una cafetería en Barcelona cuando éramos jóvenes y soñábamos con una vida más grande.",
    "ff.story2": "Al principio era solo un chiste entre amigos. Luego empecé a decirlo online, gritándolo a la cámara, y de repente gente de todo el mundo me lo gritaba de vuelta.",
    "ff.story3": "La gente me pregunta todo el tiempo qué significa realmente Fruten Fraten. La verdad es que si tienes que analizarlo demasiado, aún no lo entiendes.",
    "bar.pre": "El Lugar",
    "bar.intro": "Donde el estilo de vida Fruten Fraten cobra vida. El propio bar de Roberto en Koh Samui, Tailandia.",
    "bar.desc": "Lo que empezó como un sueño se hizo realidad en la isla de Koh Samui.",
    "bar.vibe": "Luces de neón, paredes de graffiti, cabina de DJ, y esa energía inconfundible.",
    "bar.location": "Ubicación",
    "bar.hours": "Horario",
    "bar.music": "Música",
    "bar.feature": "La Experiencia",
    "bar.cta": "Ven al bar 🔥",
    "bar.directions": "Cómo Llegar",
    "exp.hero": "Experiencia Brasil",
    "exp.title": "Un Día en Brasil",
    "exp.style": "Estilo Roberto",
    "exp.subtitle": "No es un tour. Es una experiencia real.",
    "exp.hook": "¿Alguna vez te preguntaste cómo se siente un día real en Brasil?",
    "exp.apply": "Solicitar la Experiencia",
    "exp.form.name": "Tu Nombre",
    "exp.form.dates": "Fechas de Viaje",
    "exp.form.group": "Tamaño del Grupo",
    "exp.form.vibe": "¿Qué vibra buscas?",
    "exp.form.submit": "Solicitar Tu Fecha",
    "footer.rights": "Todos los derechos reservados.",
  },
  pt: {
    "nav.about": "Sobre",
    "nav.shop": "Loja",
    "nav.videos": "Vídeos",
    "nav.destinations": "Destinos",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Experiência",
    "nav.bar": "O Bar",
    "nav.subscribe": "Inscreva-se",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Viagem. Cultura. Wolfgang.",
    "hero.shop": "Comprar Perfumes",
    "hero.youtube": "Assistir no YouTube",
    "hero.experience": "Experiência Brasil",
    "about.pre": "Quem é Roberto?",
    "about.title1": "O Homem Por Trás",
    "about.title2": "Das Missões",
    "about.quote": "Não estou tentando ser um influenciador limpo. Sou apenas um cara que se recusou a ficar onde foi colocado e decidiu transformar sua vida louca em uma história viva.",
    "about.bio1": "Cresci na Suécia, mas nunca senti que pertencia a lugar nenhum. Minhas raízes são macedônias e ciganas, minha realidade eram os subúrbios suecos, e minha cabeça estava sempre em outro lugar do mundo.",
    "about.bio2": "O Brasil mudou tudo para mim. Na primeira vez que vim, me senti mais em casa nas ruas do Rio do que jamais na Suécia. A Tailândia se tornou o outro lado da minha história.",
    "about.bio3": "Meu canal é basicamente minha vida elevada a 100. Falo muitos idiomas, conecto com pessoas rápido, e não uso roteiro. Quando você assiste Roberto Vs The World, quero que sinta que está bem do meu lado.",
    "about.subs": "Inscritos no YouTube",
    "videos.pre": "Últimas Aventuras",
    "videos.title": "Vídeos em Destaque",
    "videos.shorts": "Últimos Shorts",
    "videos.all": "Ver Todos os Vídeos",
    "videos.allShorts": "Ver Todos os Shorts",
    "shop.pre": "Coleção Exclusiva",
    "shop.title": "Perfumes Fruten Fraten®",
    "shop.subtitle": "Leve o espírito da aventura com você.",
    "shop.now": "Comprar",
    "shop.notify": "Me Notifique",
    "shop.visit": "Visitar Loja Completa",
    "ff.origin": "Nascido em um café em Barcelona — virou um movimento mundial",
    "ff.story1": "Fruten Fraten não vem de um dicionário. Inventei com um amigo em um café em Barcelona quando éramos jovens e sonhávamos com uma vida maior.",
    "ff.story2": "No começo era só uma piada interna. Depois comecei a falar online, gritando na câmera, e de repente gente do mundo todo gritava de volta.",
    "ff.story3": "As pessoas me perguntam o tempo todo o que Fruten Fraten realmente significa. A verdade é que se você precisa analisar demais, ainda não entendeu.",
    "bar.pre": "O Lugar",
    "bar.intro": "Onde o estilo de vida Fruten Fraten ganha vida. O bar do Roberto em Koh Samui, Tailândia.",
    "bar.desc": "O que começou como um sonho virou realidade na ilha de Koh Samui.",
    "bar.vibe": "Luzes neon, paredes de grafite, cabine de DJ, e aquela energia inconfundível.",
    "bar.location": "Localização",
    "bar.hours": "Horário",
    "bar.music": "Música",
    "bar.feature": "A Experiência",
    "bar.cta": "Cola no bar 🔥",
    "bar.directions": "Como Chegar",
    "exp.hero": "Experiência Brasil",
    "exp.title": "Um Dia no Brasil",
    "exp.style": "Estilo Roberto",
    "exp.subtitle": "Não é um tour. É uma experiência real.",
    "exp.hook": "Já se perguntou como é um dia real no Brasil?",
    "exp.apply": "Solicitar a Experiência",
    "exp.form.name": "Seu Nome",
    "exp.form.dates": "Datas de Viagem",
    "exp.form.group": "Tamanho do Grupo",
    "exp.form.vibe": "Que vibe você procura?",
    "exp.form.submit": "Solicitar Sua Data",
    "footer.rights": "Todos os direitos reservados.",
  },
  de: {
    "nav.about": "Über",
    "nav.shop": "Shop",
    "nav.videos": "Videos",
    "nav.destinations": "Reiseziele",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Erlebnis",
    "nav.bar": "Die Bar",
    "nav.subscribe": "Abonnieren",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Reisen. Kultur. Wolfgang.",
    "hero.shop": "Parfüms Kaufen",
    "hero.youtube": "Auf YouTube Ansehen",
    "hero.experience": "Brasilien Erleben",
    "about.pre": "Wer ist Roberto?",
    "about.title1": "Der Mann Hinter",
    "about.title2": "Den Missionen",
    "bar.pre": "Der Ort",
    "bar.intro": "Wo der Fruten Fraten Lifestyle zum Leben erwacht.",
    "bar.directions": "Wegbeschreibung",
    "footer.rights": "Alle Rechte vorbehalten.",
  },
  fr: {
    "nav.about": "À Propos",
    "nav.shop": "Boutique",
    "nav.videos": "Vidéos",
    "nav.destinations": "Destinations",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Expérience",
    "nav.bar": "Le Bar",
    "nav.subscribe": "S'abonner",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Voyage. Culture. Wolfgang.",
    "hero.shop": "Acheter Parfums",
    "hero.youtube": "Regarder sur YouTube",
    "hero.experience": "Expérience Brésil",
    "about.pre": "Qui est Roberto?",
    "about.title1": "L'Homme Derrière",
    "about.title2": "Les Missions",
    "bar.pre": "Le Lieu",
    "bar.intro": "Où le style de vie Fruten Fraten prend vie.",
    "bar.directions": "Itinéraire",
    "footer.rights": "Tous droits réservés.",
  },
  th: {
    "nav.about": "เกี่ยวกับ",
    "nav.shop": "ร้านค้า",
    "nav.videos": "วิดีโอ",
    "nav.destinations": "จุดหมาย",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "ประสบการณ์",
    "nav.bar": "บาร์",
    "nav.subscribe": "สมัครสมาชิก",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "ท่องเที่ยว. วัฒนธรรม. Wolfgang.",
    "hero.shop": "ซื้อน้ำหอม",
    "hero.youtube": "ดูบน YouTube",
    "hero.experience": "สัมผัสบราซิล",
    "about.pre": "Roberto คือใคร?",
    "about.title1": "ผู้ชายเบื้องหลัง",
    "about.title2": "ภารกิจทั้งหมด",
    "bar.pre": "สถานที่",
    "bar.intro": "ที่ซึ่งไลฟ์สไตล์ Fruten Fraten มีชีวิตชีวา บาร์ของ Roberto บนเกาะสมุย",
    "bar.directions": "เส้นทาง",
    "footer.rights": "สงวนลิขสิทธิ์.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
