import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es" | "pt" | "de" | "fr" | "th";

interface LanguageInfo {
  code: Language;
  name: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "pt", name: "Português", flag: "🇧🇷" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.about": "About",
    "nav.shop": "Shop",
    "nav.videos": "Videos",
    "nav.destinations": "Destinations",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Experience",
    "nav.subscribe": "Subscribe",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Travel. Culture. Wolfgang.",
    "hero.shop": "Shop Perfumes",
    "hero.youtube": "Watch on YouTube",
    "hero.experience": "Experience Brazil",
    "about.pre": "Who is Roberto?",
    "about.title1": "The Man Behind",
    "about.title2": "The Missions",
    "about.quote": "I want to inspire people to step out of their comfort zone, book that ticket, and live a life they actually love.",
    "about.bio1": "Born in Sweden with Macedonian roots, Roberto took the world by storm with raw, unfiltered travel content. From Rio's favelas to Bangkok's rooftops, he lives with a boldness that's magnetic — and 441K+ subscribers follow every step.",
    "about.bio2": "His channel didn't blow up from perfect production. It exploded because people recognized something real. Street vendors in Medellín, party legends in Marbella, monks in Chiang Mai — Roberto connects with everyone. That authenticity built the Wolfgang, a global tribe that rides with him on every mission.",
    "about.subs": "YouTube Subscribers",
    "videos.pre": "Latest Adventures",
    "videos.title": "Featured Videos",
    "videos.shorts": "Latest Shorts",
    "videos.all": "See All Videos",
    "dest.pre": "Where Roberto Goes",
    "dest.title": "Destinations",
    "shop.pre": "Exclusive Collection",
    "shop.title": "Fruten Fraten® Perfumes",
    "shop.subtitle": "Carry the spirit of adventure with you. Each fragrance tells a chapter of the journey.",
    "shop.now": "Shop Now",
    "shop.notify": "Notify Me",
    "shop.visit": "Visit Full Store",
    "ff.title": "Fruten Fraten",
    "ff.desc": "More than a catchphrase — it's a philosophy. It's about living in the moment, embracing the chaos, and finding joy in every corner of the world.",
    "ff.when": "When Roberto says",
    "ff.means": "it means the adventure is about to get real.",
    "ff.bold": "Live Bold",
    "ff.bold.sub": "No comfort zones allowed",
    "ff.real": "Stay Real",
    "ff.real.sub": "Authentic connections only",
    "ff.party": "Party Hard",
    "ff.party.sub": "Life is a celebration",
    "wolf.pre": "The Pack",
    "wolf.title": "Wolfgang",
    "wolf.desc": "The Wolfgang isn't just a fanbase — it's a global tribe of adventurers, dreamers, and real ones who ride with Roberto through every mission.",
    "wolf.yt.desc": "Watch the latest travel vlogs, missions, and behind-the-scenes content.",
    "wolf.ig.desc": "Follow for daily stories, travel photos, and Wolfgang updates.",
    "wolf.tt.desc": "Quick clips, viral moments, and chaotic energy from around the world.",
    "wolf.tw.desc": "Live streams, real-time adventures, and hanging with the Wolfgang.",
    "wolf.join": "Join the Pack",
    "wolf.join.desc": "Become a true Wolfgang member. Subscribe, follow, and be part of the global adventure.",
    "exp.hero": "Experience Brazil",
    "exp.title": "A Day in Brazil",
    "exp.style": "Roberto Style",
    "exp.subtitle": "Not a tour. A real experience.",
    "exp.hook": "Ever wondered what a real day in Brazil feels like?",
    "exp.desc": "Join Roberto for a half-day or full-day experience through beaches, local food spots, hidden gems, and authentic nightlife. This isn't a tour guide holding a flag. This is Brazil through real connections.",
    "exp.day": "Day Experience",
    "exp.night": "Night Experience",
    "exp.full": "Full Roberto Mode",
    "exp.apply": "Apply for the Experience",
    "exp.form.name": "Your Name",
    "exp.form.dates": "Travel Dates",
    "exp.form.group": "Group Size",
    "exp.form.vibe": "What vibe are you looking for?",
    "exp.form.submit": "Request Your Date",
    "footer.rights": "All rights reserved.",
  },
  es: {
    "nav.about": "Acerca de",
    "nav.shop": "Tienda",
    "nav.videos": "Videos",
    "nav.destinations": "Destinos",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Experiencia",
    "nav.subscribe": "Suscríbete",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Viaje. Cultura. Wolfgang.",
    "hero.shop": "Comprar Perfumes",
    "hero.youtube": "Ver en YouTube",
    "hero.experience": "Experiencia Brasil",
    "about.pre": "¿Quién es Roberto?",
    "about.title1": "El Hombre Detrás",
    "about.title2": "De Las Misiones",
    "about.quote": "Quiero inspirar a la gente a salir de su zona de confort, comprar ese boleto y vivir una vida que realmente amen.",
    "about.bio1": "Nacido en Suecia con raíces macedonias, Roberto conquistó el mundo con contenido de viaje crudo y sin filtros. Desde las favelas de Río hasta los tejados de Bangkok, vive con una audacia que es magnética — y más de 441K suscriptores siguen cada paso.",
    "about.bio2": "Su canal no explotó por una producción perfecta. Explotó porque la gente reconoció algo real. Vendedores ambulantes en Medellín, leyendas de fiestas en Marbella, monjes en Chiang Mai — Roberto conecta con todos. Esa autenticidad construyó el Wolfgang, una tribu global.",
    "about.subs": "Suscriptores de YouTube",
    "videos.pre": "Últimas Aventuras",
    "videos.title": "Videos Destacados",
    "videos.shorts": "Últimos Shorts",
    "videos.all": "Ver Todos los Videos",
    "dest.pre": "A Dónde Va Roberto",
    "dest.title": "Destinos",
    "shop.pre": "Colección Exclusiva",
    "shop.title": "Perfumes Fruten Fraten®",
    "shop.subtitle": "Lleva el espíritu de la aventura contigo. Cada fragancia cuenta un capítulo del viaje.",
    "shop.now": "Comprar",
    "shop.notify": "Notificarme",
    "shop.visit": "Visitar Tienda Completa",
    "exp.hero": "Experiencia Brasil",
    "exp.title": "Un Día en Brasil",
    "exp.style": "Estilo Roberto",
    "exp.subtitle": "No es un tour. Es una experiencia real.",
    "exp.hook": "¿Alguna vez te preguntaste cómo se siente un día real en Brasil?",
    "exp.apply": "Solicitar la Experiencia",
    "footer.rights": "Todos los derechos reservados.",
  },
  pt: {
    "nav.about": "Sobre",
    "nav.shop": "Loja",
    "nav.videos": "Vídeos",
    "nav.destinations": "Destinos",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Experiência",
    "nav.subscribe": "Inscreva-se",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Viagem. Cultura. Wolfgang.",
    "hero.shop": "Comprar Perfumes",
    "hero.youtube": "Assistir no YouTube",
    "hero.experience": "Experiência Brasil",
    "about.pre": "Quem é Roberto?",
    "about.title1": "O Homem Por Trás",
    "about.title2": "Das Missões",
    "about.quote": "Quero inspirar as pessoas a sair da zona de conforto, comprar aquela passagem e viver a vida que realmente amam.",
    "about.bio1": "Nascido na Suécia com raízes macedônias, Roberto conquistou o mundo com conteúdo de viagem cru e sem filtros. Das favelas do Rio aos telhados de Bangkok, ele vive com uma ousadia que é magnética — e mais de 441K inscritos seguem cada passo.",
    "about.bio2": "Seu canal não explodiu por produção perfeita. Explodiu porque as pessoas reconheceram algo real. Vendedores ambulantes em Medellín, lendas de festas em Marbella, monges em Chiang Mai — Roberto conecta com todos. Essa autenticidade construiu o Wolfgang, uma tribo global.",
    "about.subs": "Inscritos no YouTube",
    "videos.pre": "Últimas Aventuras",
    "videos.title": "Vídeos em Destaque",
    "videos.shorts": "Últimos Shorts",
    "videos.all": "Ver Todos os Vídeos",
    "dest.pre": "Onde Roberto Vai",
    "dest.title": "Destinos",
    "shop.pre": "Coleção Exclusiva",
    "shop.title": "Perfumes Fruten Fraten®",
    "shop.subtitle": "Leve o espírito da aventura com você. Cada fragrância conta um capítulo da jornada.",
    "shop.now": "Comprar",
    "shop.notify": "Me Notifique",
    "shop.visit": "Visitar Loja Completa",
    "exp.hero": "Experiência Brasil",
    "exp.title": "Um Dia no Brasil",
    "exp.style": "Estilo Roberto",
    "exp.subtitle": "Não é um tour. É uma experiência real.",
    "exp.hook": "Já se perguntou como é um dia real no Brasil?",
    "exp.apply": "Solicitar a Experiência",
    "footer.rights": "Todos os direitos reservados.",
  },
  de: {
    "nav.about": "Über",
    "nav.shop": "Shop",
    "nav.videos": "Videos",
    "nav.destinations": "Reiseziele",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Erlebnis",
    "nav.subscribe": "Abonnieren",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Reisen. Kultur. Wolfgang.",
    "hero.shop": "Parfüms Kaufen",
    "hero.youtube": "Auf YouTube Ansehen",
    "hero.experience": "Brasilien Erleben",
    "about.pre": "Wer ist Roberto?",
    "about.title1": "Der Mann Hinter",
    "about.title2": "Den Missionen",
    "footer.rights": "Alle Rechte vorbehalten.",
  },
  fr: {
    "nav.about": "À Propos",
    "nav.shop": "Boutique",
    "nav.videos": "Vidéos",
    "nav.destinations": "Destinations",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "Expérience",
    "nav.subscribe": "S'abonner",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "Voyage. Culture. Wolfgang.",
    "hero.shop": "Acheter Parfums",
    "hero.youtube": "Regarder sur YouTube",
    "hero.experience": "Expérience Brésil",
    "about.pre": "Qui est Roberto?",
    "about.title1": "L'Homme Derrière",
    "about.title2": "Les Missions",
    "footer.rights": "Tous droits réservés.",
  },
  th: {
    "nav.about": "เกี่ยวกับ",
    "nav.shop": "ร้านค้า",
    "nav.videos": "วิดีโอ",
    "nav.destinations": "จุดหมาย",
    "nav.wolfgang": "Wolfgang",
    "nav.experience": "ประสบการณ์",
    "nav.subscribe": "สมัครสมาชิก",
    "hero.subtitle": "Roberto Vs The World",
    "hero.tagline": "ท่องเที่ยว. วัฒนธรรม. Wolfgang.",
    "hero.shop": "ซื้อน้ำหอม",
    "hero.youtube": "ดูบน YouTube",
    "hero.experience": "สัมผัสบราซิล",
    "about.pre": "Roberto คือใคร?",
    "about.title1": "ผู้ชายเบื้องหลัง",
    "about.title2": "ภารกิจทั้งหมด",
    "footer.rights": "สงวนลิขสิทธิ์.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
